let params = {
    source_object : "tsys_dispcases_clean",
    source_dataset: 'raw',
    dataset: "trusted",
    object_name: 'tsys_dispcases',
    object_description: 'Tabela contém dados do caso de disputa criado, incluindo dados de entrada do operador, dados da transação de início e posterior resolução.',
    type: "upsert",
    key_columns: ["institution_id","serno"],
    watermark_columns: ["ingestion_ref_date"],
    incremental_watermark: "ingestion_timestamp",
    partition_by: {column:"ingestion_timestamp", type: "timestamp", granularity: "day"},
    cluster_by: ["ingestion_ref_date"],
    developer: ["matheus_felippe_silva_ext@carrefour.com"],
    pec: 2,
    pec_obs: 'PIT 0002 - Tsys',  
    custom_tags:['PIT0002'],
    columns: ["*"] ,
    columns_description: {
      type: 'Tipo de operação referente ao registro: I-Insert, U-Update, D-Delete, F-Carga Full',
      institution_id: 'IDn da instituição Usado para suporte a várias instituições. (Institution IDn Used for multi institution support)',
      serno: 'Numero sequencial unico gerado pela Tsys. (Record serial number)',
      partitionkey: 'Chave usada para particionar a tabela. Os valores atribuídos a esse campo dependerão da estratégia de arquivamento. (Key used to partition the table. The values assigned to this field will depend on the archiving strategy)',
      amount: 'Valor do caso de disputa. (Case amount)',
      currency: 'Valor da moeda do caso. (Case amount currency)',
      disputereason: 'Razão da disputa. (Dispute reaason)',
      notificationmeans: 'Como a disputa foi iniciada, ou seja, telefone, carta etc.(How dispute was initiated, i.e. phone, letter etc.)',
      notificationdate: 'Data de inicio da disputa automatica, ou data em que o operador notifica a disputa. (Date dispute got initiated for autoamtic dispute or date operator was notified of the dispute)',
      fraud: 'Indicador para verificar se a disputa é relacionada a fraude: 1 - Fraude, 0 - Não fraude. (Flag to indicate if dispute is fraud related: 1 - Fraud, 0 - Non fraud)',
      fraudreason: 'Razão de fraude, VISA: código de notificação de fraude, MasterCard: tipo de fraude SAFE. (Fraud reason, VISA: Fraud advice notification code, MasterCard: SAFE fraud type)',
      sysdomain: 'Domínio do sistema de disputa: I - emissor, A - adquirente. (Dispute system domain: I - issuer, A - acquirer)',
      paysys: 'Sistema de pagamento. (Payment system)',
      onus: 'Indicador para sinalizar se a disputa é OnUs: 1 - On Us, 0 - Off Us',
      cardholdername: 'Nome do titular do cartão. (Name of the cardholder)',
      cardnumber: 'Número do cartão. (Card number)',
      trxndate: 'Data de transação. (Transaction date)',
      merchantid: 'ID do Estabelecimento. (Merchant id)',
      merchantname: 'Nome do Estabelecimento. (Merchant name)',
      arn: 'Número de referência do adquirente. (Acquirer reference number)',
      mcc: 'Código de categoria do estabelecimento. (Merchant cetegory code)',
      posentrycode: 'Código de entrada POS, i022_pos_entry. (POS Entry code, i022_pos_entry)',
      instalmenttype: 'Tipo de parcela 0 - Emissor, 1 - Adquirente, Nula - transação não parcelada. (Type of instalment 0 - Issuer, 1 - Acquirer, Null - non-instalment transaction)',
      instalmentseq: 'Sequência da parcela. (Sequence of the instalment)',
      accserno: 'Link para a tabela de contas para disputas de emissão (caccounts) e de aquisição (meraccounts)(FK). (Link to the account table, for issuing(caccounts) and acquirung(meraccounts) disputes)',
      cardserno: 'Link para a tabela de cartões, para emissão de disputas (FK tabela de cartoes). (Link to the card table, for issuing disputes)',
      merserno: 'Link para a tabela de localização do estabelecimento, para aquisição e emissão de disputas de ONUS. (Link to the merchant location table, for acquirung and issuing onus disputes)',
      trxnserno: 'Número de série da transação original da disputa. (FK CTRANSACTIONS). (Serial number of the dispute original transaction)',
      trxnpartitionkey: 'Chave de partição da transação original da disputa. (Partition key of the dispute original transaction)',
      trxnsubpartitionkey: 'Chave da partição secundária da transação original da disputa. (Sub partition key of the dispute original transaction)',
      authserno: 'número de série da autorização (SERNO da autorizacao). (authorization serial number)',
      restype1: 'O primeiro tipo de resolução. Indica se o caso foi resolvido automaticamente ou manualmente e se manualmente o caminho seguido. (The first resolution type. Indicates if case was resolved automatically or manually and if manually the path followed)',
      resreason1: 'O primeiro motivo de resolução. Se a resolução automática, então este será o id da regra, se manualmente será o motivo de resolução selecionado pelo usuário. (The first resoulution reason. If automatic resolution then this willbe the rule id, if manually it will be the resolution reason selected by the user)',
      restype2: 'O segundo tipo de resolução. Indica se o caso foi resolvido automaticamente ou manualmente e se manualmente o caminho seguido. (The second resolution type. Indicates if case was resolved automatically or manually and if manually the path followed)',
      resreason2: 'A segunda razão de resolução. Se a resolução automática, então este será o id da regra, se manualmente será o motivo de resolução selecionado pelo usuário. (The second resolution reason. If automatic resolution then this willbe the rule id, if manually it will be the resolution reason selected by the user)',
      cbkrefnum: 'Número de referência do estorno. (Chargeback reference number)',
      externalrefnum: 'Número de referência do sistema externo. Para VISA é o número do processo VISA (de VROL) e para DINERS o número de referência Xchange. (External system reference number. For VISA is the VISA case number (from VROL) and for DINERS the Xchange reference number)',
      phasedate: 'A data da fase atual do caso de disputa. (The date of the current dispute case phase)',
      cpd:'Data Central de Processamento (CPD) da transação disputada.'
    },
    
    data_governance: [
      {name: "schedule_name", value: "tsys_dispcases"},
      {name: "data_classification", value: "Internal"},
      {name: "partitioned_table", value: "true"},
      {name: "clustered_table", value: "true"},
      {name: "update_frequency", value: "Daily"},
      {name: "load_type", value: "Incremental"},
      {name: "data_retention", value: "Not Applicable"}],

    data_governance_column: [
      {column:'cardholdername', name:'pii', value:'true'},
      {column:'cardnumber', name:'pii', value:'true'}
    ],
    
    policy_tags: {
      cardholdername: 'pii',
      cardnumber: 'pii',
    }
}

csf_modules.deduplication.dedup(params)
